### ISSUE TITLE
TypeError using ChakraCoreJsEngine

### ISSUE THREAD

**Issue by stefanloerwald** [Taritsyn/AutoprefixerHost#1]
With version 2.0.2 (using ChakraCoreJsEngine), I get

```
TypeError: Object expected
   at loadFile (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:103762) -> …th,inputSourceMapContent){var result,postCssOptions,sourceMapOptions,autoprefixerOptions,autoprefixe
   at loadMap (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:104679)
   at PreviousMap (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:102042)
   at Input (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:105723)
   at parse$3 (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:107724)
   at LazyResult$1 (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:110048)
   at process (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:120803)
   at process (AutoprefixerHost.Resources.autoprefixer-combined.min.js:16:935009)
   at AutoprefixerHelper.prototype.process (AutoprefixerHost.Resources.autoprefixerHelper.min.js:1:1801)
   at Global code (Script Document [2]:1:1)
```

for the input file

```css
@charset "UTF-8";
div {
  background: url(../foo.png); }

body {
  background-color: blue;
  content: "✔ æøå"; }

#test1 {
  color: red; }

/*#test2{
    color: blue;
}*/
#test3 {
  color: green;
  transition: all .5s; }

.parent .child {
  width: 64px;
  height: 24px; }

/*# sourceMappingURL=test.scss */
```

It worked fine with v2.0.1. Not sure where the issue is... Thanks for any help.
